### ISSUE TITLE
Seasons being named with series name instead of "Season N"

### ISSUE THREAD

**Issue by ayyu** [jellyfin/jellyfin-plugin-anilist#10]
When identifying a series using this plugin, the Season is named with the actual name of the series instead of the season number:
![image](https://user-images.githubusercontent.com/11494813/121109553-cca30b00-c7d9-11eb-94fb-40aff0329d8c.png)

This isn't so bad until identifying a multi-season show:
![image](https://user-images.githubusercontent.com/11494813/121109715-1986e180-c7da-11eb-8e97-f9a15d7b7cec.png)

I think this broke somewhere along the move to 10.7 but I'm too dumb to figure out why

**Comment by sqlstatement** [comment]
Are you sure it's this plugin causing it? As far as I'm aware, the AniList API doesn't even have season names, and the naming for my seasons under 10.7.5 is like I expect it to be
![image](https://user-images.githubusercontent.com/27446425/121735399-5e6e8900-caf6-11eb-83ad-0d50a595248f.png)

**Comment by ayyu** [comment]
I think you're right and it's some other plugin screwing everything up, since it doesn't happen consistently. Must be another provider.
