### ISSUE TITLE
Cannot manually set AniList Series Id

### ISSUE THREAD

**Issue by winterbird-code** [jellyfin/jellyfin-plugin-anilist#33]
This is a bit weird problem, but I'm reasonable certain it's an issue with this plugin. When an ID isn't automatically assigned I cannot manually set the ID (or maybe the automatic detection can't either, and that's why it's empty?)

Anyway I have at least two shows with this issue (but probably quite a lot more as it's a newly imported library and I only did a quick sanity check). These are the AniDB names and exact names of the folders:

- 100-man no Inochi no Ue ni Ore wa Tatte Iru (2021) 
- Ai Shoujo Pollyanna Story

These shows has anilist ID 127366 and 2554, but neither was detected (AniList ID was empty). When I try to manually set the ID:s the jellyfin webpage hang with the "I'm busy working"-wheel spinning. Nothing happens in the logs, and the ID is never registered on the show. I've tried both from the global metadata editor page and by choosing "Edit metadata" on the series page.

Meanwhile, "Aa! Megami-sama! (2005)" was mistakenly identified as ID 9611 (which is "Aa! Megami-sama! (2011) ", correct ID should be 50). Changing this ID to the correct one could be done without any problems.

Just to test, I tried to set one of the problematic shows to ID 50 as this worked on "Aa! Megami-sama! (2005)". It still didn't work on on this show though...

Jellyfin is version 10.8.1 and the library uses these metadata plugins (in order):

- AniDB-6.0.0.0
- AniList-5.0.0.0
- TheTVDB-8.0.0.0
- TheMovieDb-10.8.1.0
- The Open Movie Database-10.8.1.0

**Comment by nevrending** [comment]
Perhaps try adding the show ID in the folder name as `[anilistid-<ID>]`
A show ID is the number bit in a AniList URL. E.g:
- If a URL is: https://anilist.co/anime/20968/Kokoro-ga-Sakebitagatterun-da/
- Then a folder name is: Hello World (2019) [anilistid-106240]

Then do a library metadata refresh

Did this to a couple of items not detected properly in my library.
Yes it did make some folder names a bit cluttered though.

**Comment by winterbird-code** [comment]
Sorry I forgot about this issue. It turns out it's most likely not an anilist issue, but a jellyfin and/or reverse-proxy issue. I managed to work around it by removing all "People"-metadata before saving. My best guess is that something fails when trying to submit lots of metadata (either at the jellyfin end or in my specific reverse-proxy setup).

So if anyone stumbles over the same problem: Try to remove some metadata before saving, and then do a manual refresh afterwards to re-add it and you should be good to go :smiley:
