### ISSUE TITLE
Don't download 'no image' images for people

### ISSUE THREAD

**Issue by sjorge** [jellyfin/jellyfin-plugin-anilist#74]
<img width="1405" alt="Screenshot 2024-07-12 at 12 59 59" src="https://github.com/user-attachments/assets/474821cf-d6d3-4a5b-a0a3-873fdbdb94f4">

Ref: https://anilist.co/staff/115997/Kinosaki-Michiru

Some people will have a `no image` image downloaded by this provider. These should not be downloaded, giving other providers that do have an image a chance to download one.

**Comment by HansLehnert** [comment]
I had addressed this in #56, but the PR got closed for seemingly no reason...

**Comment by sjorge** [comment]
Weird that it got closed, maybe aks why in the PR. Maybe it was an error.

**Comment by nielsvanvelzen** [comment]
The pull request was targeting the unstable branch which was auto-deleted once 10.9 was released. I'm confident it was accidental. You can re-open it but target the master branch instead!

**Comment by sjorge** [comment]
PR got merged, closing
